name: release

permissions: write-all

on:
  push:
    paths: package.json

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: npm-${{ hashFiles('bun.lockb') }}

      - name: Set up bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun i

      - name: Run linters
        run: bun run lint

      - name: Run tests
        run: bun run test

      - name: Release
        run: ./.github/release.sh
        env:
          ASSET_NAME: TODO
          GH_TOKEN: ${{ github.token }}
          # NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
